### ISSUE TITLE
Corrupt or unknown file format

### ISSUE THREAD

**Issue by gzYou** [canaltinigne/HeightWeightFinder#2]
When I downloaded and tried to unzip the pretrained weights file, it says Corrupt or unknown file format

**Comment by canaltinigne** [comment]
Hi,

There was an issue with model path. I fixed it now, and it runs on my local. Can you now try putting `pth.tar` files in `/models` folder ?

**Comment by gzYou** [comment]
Thank you!  As you said, I corrected the file path and the problem was solved.
